import type { InterviewQuestion } from "./questions.ts";

type PythonQuestion = Omit<InterviewQuestion, "translations">;

const source = (title: string, url: string) => ({ title, url });
let nextQuestionNumber = 1;

const question = (
  _sourceId: string,
  topicId: string,
  slug: string,
  difficulty: PythonQuestion["difficulty"],
  prompt: string,
  shortAnswer: string,
  explanation: string,
  sourceTitle: string,
  sourceUrl: string,
  codeExample?: string,
): PythonQuestion => ({
  id: `python-${String(nextQuestionNumber++).padStart(3, "0")}`,
  slug,
  trackId: "python",
  topicIds: [topicId],
  difficulty,
  question: prompt,
  shortAnswer,
  explanation,
  ...(codeExample ? { codeExample } : {}),
  sources: [source(sourceTitle, sourceUrl)],
  lastReviewedAt: "2026-09-10",
});

export const pythonBaseQuestions: PythonQuestion[] = [
  // Python fundamentals
  question("fund-001", "python-fundamentals", "python-interpreter-bytecode-and-vm", "Junior", "إيه اللي بيحصل للكود في Python من لحظة تشغيله؟", "Python يقرأ المصدر ويحوّله عادةً إلى bytecode ثم ينفذه الـ interpreter داخل العملية.", "وجود bytecode لا يعني أن Python لغة compiled بالطريقة نفسها التي تُبنى بها لغة native؛ الهدف هو تمثيل وسيط يُنفذ بواسطة Python runtime، وقد تختلف التفاصيل حسب التنفيذ مثل CPython.", "Python tutorial — Using the Python interpreter", "https://docs.python.org/3/tutorial/interpreter.html"),
  question("fund-002", "python-fundamentals", "python-mutable-vs-immutable-values", "Junior", "ما الفرق بين mutable وimmutable في Python؟", "الكائن mutable يمكن تغيير محتواه، أما immutable فلا يتغير بعد إنشائه؛ إعادة الإسناد تنشئ ارتباطًا جديدًا.", "القائمة والقاموس mutable، بينما str وtuple وint immutable. الفرق مهم عند مشاركة نفس الكائن بين متغيرات أو استخدامه كمفتاح في dict؛ لا تخلط بين تغيير الكائن وتغيير اسم المتغير.", "Python documentation — Data model", "https://docs.python.org/3/reference/datamodel.html"),
  question("fund-003", "python-fundamentals", "python-list-tuple-set-dict-choice", "Junior", "إمتى تختار list أو tuple أو set أو dict؟", "استخدم list للترتيب القابل للتغيير، tuple لسجل ثابت، set للعضوية بدون تكرار، وdict للربط بين مفتاح وقيمة.", "اختيار البنية يجب أن يعكس العقد المطلوب: هل تحتاج ترتيبًا، membership سريعًا، uniqueness، أم lookup بمفتاح؟ لا تستخدم set عندما تكون المحافظة على ترتيب البيانات جزءًا من الواجهة.", "Python tutorial — Data structures", "https://docs.python.org/3/tutorial/datastructures.html"),
  question("fund-004", "python-fundamentals", "python-comprehensions-readability", "Junior", "إيه استخدام list وdict comprehensions وإمتى تبقى زيادة؟", "هي صيغة مختصرة لبناء collection من iterable مع تحويل أو filter بسيط.", "تكون مفيدة عندما تبقى العملية مقروءة في سطر واحد. لو زادت الشروط أو تداخلت الحلقات، استخدم حلقة عادية أو دالة مسماة؛ الاختصار ليس مكسبًا إذا أخفى logic مهمًا.", "Python tutorial — List comprehensions", "https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions", "squares = {n: n * n for n in range(5) if n % 2 == 0}"),
  question("fund-005", "python-fundamentals", "python-is-vs-equality", "Junior", "ما الفرق بين is و== في Python؟", "== يقارن القيمة، بينما is يتحقق هل الاسمان يشيران إلى نفس الكائن.", "استخدم is غالبًا مع None مثل value is None. لا تعتمد على interning أو caching لبعض الأعداد والنصوص لإثبات تطابق القيم؛ هذه تفاصيل تنفيذ وليست مقارنة قيمة.", "Python documentation — Comparisons", "https://docs.python.org/3/reference/expressions.html#comparisons"),
  question("fund-006", "python-fundamentals", "python-truth-value-testing", "Junior", "إزاي Python يحدد إن القيمة truthy أو falsy؟", "الكائن يكون falsy إذا عرّف __bool__ ترجع False أو __len__ ترجع صفر، وبعض القيم الأساسية مثل None و0 وempty collections falsy.", "اختبر الحالة مباشرة في if بدل مقارنة كل collection بـ[] أو كل رقم بـ0. لو أنشأت class، عرّف truthiness فقط عندما يكون لها معنى واضح ولا تجعلها تخفي خطأ في البيانات.", "Python documentation — Truth value testing", "https://docs.python.org/3/library/stdtypes.html#truth-value-testing"),
  question("fund-007", "python-fundamentals", "python-unpacking-and-starred-expressions", "Junior", "ما فائدة unpacking وstarred expressions؟", "تسمح بتوزيع عناصر iterable على متغيرات، مع استخدام * لالتقاط عدد متغير من العناصر.", "unpacking يجعل حدود البيانات صريحة، لكنه يفترض عددًا مناسبًا من العناصر. استخدمه مع tuples أو نتائج معروفة، وتعامل مع الحالات الديناميكية بدل الاعتماد على ترتيب غير مضمون.", "Python tutorial — More on lists", "https://docs.python.org/3/tutorial/datastructures.html#more-on-lists", "first, *middle, last = [1, 2, 3, 4]"),
  question("fund-008", "python-fundamentals", "python-slicing-copy-semantics", "Junior", "ماذا يفعل slicing في list وstr وهل ينتج نسخة؟", "slicing ينشئ object جديدًا من الجزء المطلوب في الأنواع المعتادة مثل list وstr، لكنه لا يعمل deep copy للعناصر الداخلية.", "نسخ list بـitems[:] ينسخ الحاوية فقط؛ إذا احتوت على lists أخرى فستظل العناصر الداخلية مشتركة. استخدم copy أو deepcopy عندما يكون ذلك مقصودًا، واحسب كلفة النسخ للبيانات الكبيرة.", "Python documentation — Common sequence operations", "https://docs.python.org/3/library/stdtypes.html#common-sequence-operations"),
  question("fund-009", "python-fundamentals", "python-import-module-package-basics", "Mid", "إيه الفرق بين module وpackage وإزاي import بيشتغل بشكل آمن؟", "module ملف Python، وpackage مجموعة modules منظمة؛ import يحل الاسم ويحمّل module مرة ثم يعيد استخدامه من cache العملية.", "نظّم imports في مستوى الملف، وتجنب تنفيذ side effects ثقيلة عند import. ضع نقطة التشغيل داخل if __name__ == \"__main__\" حتى يمكن استيراد module من غير تشغيل CLI بالخطأ.", "Python tutorial — Modules", "https://docs.python.org/3/tutorial/modules.html", "if __name__ == \"__main__\":\n    main()"),
  question("fund-010", "python-fundamentals", "python-name-main-entry-point", "Junior", "ليه بنستخدم if __name__ == '__main__'؟", "لتمييز تشغيل الملف مباشرة عن استيراده كـmodule.", "عند التشغيل المباشر تكون قيمة __name__ هي __main__، وعند import تكون اسم module. هذا النمط يفصل قابلية الاستيراد عن CLI ويجعل الاختبار وإعادة الاستخدام أسهل.", "Python tutorial — Command-line arguments", "https://docs.python.org/3/tutorial/stdlib.html#command-line-arguments"),

  // Python data model and object model
  question("model-001", "python-data-model", "python-eq-hash-contract", "Senior", "ما العلاقة بين __eq__ و__hash__ في Python؟", "إذا تساوى كائنان يجب أن تكون لهما نفس hash، والكائن القابل للاستخدام كمفتاح يجب ألا يتغير الجزء الذي تعتمد عليه المقارنة أثناء وجوده في dict أو set.", "تعريف __eq__ وحده قد يجعل الكائن غير قابل للـhash في Python. لا تجعل hash يعتمد على mutable state، وإلا قد يضيع المفتاح منطقيًا داخل المجموعة رغم بقائه في الذاكرة.", "Python documentation — object.__hash__", "https://docs.python.org/3/reference/datamodel.html#object.__hash__"),
  question("model-002", "python-data-model", "python-shallow-vs-deep-copy", "Mid", "ما الفرق بين shallow copy وdeep copy؟", "shallow copy ينسخ الحاوية ويشارك العناصر الداخلية، أما deep copy فيحاول نسخ graph الكائنات recursively.", "ابدأ بالنسخ السطحي عندما تكون العناصر immutable أو المشاركة مقصودة. deep copy قد يكون مكلفًا أو غير مناسب لكائنات مثل handles وlocks؛ الأفضل أحيانًا بناء DTO جديد بالحقول المطلوبة.", "Python documentation — copy", "https://docs.python.org/3/library/copy.html", "from copy import copy, deepcopy\nshallow = copy(value)\ndeep = deepcopy(value)"),
  question("model-003", "python-data-model", "python-iterable-vs-iterator", "Junior", "ما الفرق بين iterable وiterator؟", "iterable يمكن إنشاء iterator منه، بينما iterator يملك __next__ ويحفظ موضعه ويُستهلك تدريجيًا.", "list iterable ويمكن عمل iter منها أكثر من مرة، أما iterator نفسه فيتقدم مع next وقد ينتهي. هذا الفرق يفسر لماذا تمرير generator إلى دالتين قد يجعل الثانية ترى بيانات أقل أو لا ترى شيئًا.", "Python documentation — Iterator types", "https://docs.python.org/3/library/stdtypes.html#iterator-types"),
  question("model-004", "python-data-model", "python-generator-yield-lazy-evaluation", "Mid", "إزاي generator وyield يقللوا استهلاك الذاكرة؟", "generator ينتج قيمة عند الطلب بدل إنشاء collection كاملة مرة واحدة.", "yield يوقف الدالة ويحفظ حالتها، ثم يكملها عند next. هذا مناسب للملفات والتدفقات الكبيرة، لكنه لا يسمح بالـrandom access ويجعل الأخطاء تظهر أثناء الاستهلاك لا وقت إنشاء generator.", "Python documentation — Generator expressions", "https://docs.python.org/3/reference/expressions.html#generator-expressions", "def rows(items):\n    for item in items:\n        yield normalize(item)"),
  question("model-005", "python-data-model", "python-iter-next-protocol", "Mid", "ما البروتوكول الذي يجعل object قابلًا للاستخدام في for؟", "يحتاج الكائن إلى __iter__ يعيد iterator، والـiterator يحتاج __next__ ويرمي StopIteration عند النهاية.", "for يخفي استدعاءات iter وnext وStopIteration. الالتزام بالبروتوكول يسمح لك ببناء collections lazy، لكن لا تخلط iterator state داخل object تريد تكراره مستقلًا أكثر من مرة.", "Python documentation — Iterator protocol", "https://docs.python.org/3/library/stdtypes.html#iterator-types"),
  question("model-006", "python-data-model", "python-property-descriptor-use", "Mid", "إمتى تستخدم property بدل getter وsetter صريحين؟", "property تعرض method كأنها attribute مع إبقاء validation أو حساب lazy خلف نفس الواجهة.", "استخدمها عندما يكون السلوك جزءًا طبيعيًا من قيمة الكائن. لا تجعل property تنفذ I/O أو عملًا مفاجئًا؛ قراءة attribute يجب أن تبقى رخيصة أو يكون ذلك واضحًا في العقد.", "Python documentation — Built-in functions: property", "https://docs.python.org/3/library/functions.html#property", "class User:\n    @property\n    def display_name(self):\n        return f\"{self.first} {self.last}\""),
  question("model-007", "python-data-model", "python-dataclass-generated-methods", "Junior", "إيه اللي بتقدمه @dataclass؟", "تولّد methods شائعة مثل __init__ و__repr__ و__eq__ بناءً على fields المعلنة.", "dataclass تقلل boilerplate لبيانات ذات semantics واضحة. حدد frozen أو order أو default_factory حسب العقد، ولا تستخدمها لإخفاء invariants معقدة تحتاج constructor أو factory يتحقق منها.", "Python documentation — dataclasses", "https://docs.python.org/3/library/dataclasses.html", "from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Point:\n    x: int\n    y: int"),
  question("model-008", "python-data-model", "python-slots-memory-and-constraints", "Senior", "ما فائدة __slots__ وما التنازلات؟", "__slots__ تحدد attributes المسموح بها وقد تمنع __dict__ لكل instance، فتقلل overhead في حالات كثيرة.", "slots ليست تحسينًا تلقائيًا؛ قد تعقّد inheritance وserialization وتمنع attributes ديناميكية أو weak references ما لم تُضف صراحة. قِس الذاكرة والسرعة قبل استخدامها على نطاق واسع.", "Python documentation — __slots__", "https://docs.python.org/3/reference/datamodel.html#object.__slots__"),
  question("model-009", "python-data-model", "python-mro-super-and-multiple-inheritance", "Senior", "إزاي MRO وsuper يشتغلوا مع multiple inheritance؟", "MRO يحدد ترتيب البحث عن methods، وsuper ينتقل للعنصر التالي في هذا الترتيب بدل استدعاء parent ثابت بالاسم.", "التصميم التعاوني يحتاج أن كل class يستدعي super ويتفق على signature. لا تستخدم multiple inheritance لمجرد إعادة استخدام كود؛ mixins الصغيرة ذات العقد الواضح أقل مفاجأة.", "Python documentation — Method resolution order", "https://docs.python.org/3/howto/mro.html"),
  question("model-010", "python-data-model", "python-context-manager-protocol", "Mid", "ما البروتوكول الذي يطبقه context manager؟", "يعرّف __enter__ و__exit__ أو يُبنى عبر contextlib لإدارة setup وcleanup حول with.", "with يضمن استدعاء cleanup حتى عند حدوث exception. يجب أن يكون __exit__ صريحًا في قرار ابتلاع الاستثناء؛ إرجاع True يخفيه، بينما False أو None يسمح بانتشاره.", "Python documentation — With statement", "https://docs.python.org/3/reference/compound_stmts.html#the-with-statement", "with resource() as value:\n    use(value)"),

  // Functions and functional patterns
  question("func-001", "python-functions", "python-positional-only-keyword-only-parameters", "Mid", "إيه الفرق بين positional-only وkeyword-only parameters؟", "الفاصل / يمنع تمرير ما قبله باسم، والفاصل * يجبر ما بعده على التمرير باسم.", "هذه القيود تثبت API وتسمح بتغيير أسماء parameters الداخلية أو منع الالتباس بين arguments. استخدمها في الدوال العامة عندما يكون شكل الاستدعاء جزءًا مهمًا من العقد.", "Python documentation — Function definitions", "https://docs.python.org/3/reference/compound_stmts.html#function-definitions", "def connect(host, /, port=443, *, timeout=5):\n    ..."),
  question("func-002", "python-functions", "python-mutable-default-argument-trap", "Junior", "ليه default list في function argument مشكلة؟", "الـdefault expression تُقيّم مرة عند تعريف الدالة، لذلك قد تُشارك نفس القائمة بين الاستدعاءات.", "استخدم None أو sentinel ثم أنشئ list داخل الدالة. هذا يحافظ على state المقصودة خارج الدالة ويمنع تسرب بيانات استدعاء إلى استدعاء آخر.", "Python FAQ — Mutable default arguments", "https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects"),
  question("func-003", "python-functions", "python-args-kwargs-api-forwarding", "Junior", "إزاي *args و**kwargs بيشتغلوا؟", "*args يجمع positional arguments في tuple، و**kwargs يجمع keyword arguments في dict، ويمكن استخدامهما لفك القيم عند الاستدعاء.", "استخدمهما عندما تكون الدالة wrapper أو forwarding layer، لكن لا تجعل signature غامضة في domain APIs. يمكن دمجهما مع keyword-only parameters لتقييد ما تقبله الدالة.", "Python tutorial — Arbitrary argument lists", "https://docs.python.org/3/tutorial/controlflow.html#arbitrary-argument-lists", "def log_event(name, *args, **kwargs):\n    return emit(name, *args, **kwargs)"),
  question("func-004", "python-functions", "python-closures-and-late-binding", "Mid", "ما هي closure وإيه مشكلة late binding في loops؟", "closure تحتفظ بالـenclosing scope، لكن القيم الحرة تُقرأ عند الاستدعاء؛ لذلك قد ترى كل callbacks آخر قيمة في loop.", "ثبّت القيمة في default argument أو استخدم factory تنشئ scope جديدًا. هذا يوضح هل تريد قراءة قيمة متغيرة لاحقًا أم snapshot وقت إنشاء callback.", "Python FAQ — Lambda expressions", "https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result", "callbacks = [lambda n=n: n for n in range(3)]"),
  question("func-005", "python-functions", "python-decorators-and-functools-wraps", "Mid", "إزاي تعمل decorator يحافظ على metadata للدالة؟", "استخدم decorator يعيد wrapper ويطبق functools.wraps على wrapper.", "بدون wraps ستفقد __name__ وdocstring وقد تربك أدوات introspection والاختبار. decorator يجب أن يبقى صغيرًا وواضحًا، خصوصًا عندما يضيف logging أو authorization أو caching.", "Python documentation — functools.wraps", "https://docs.python.org/3/library/functools.html#functools.wraps", "from functools import wraps\n\ndef traced(fn):\n    @wraps(fn)\n    def wrapper(*args, **kwargs):\n        return fn(*args, **kwargs)\n    return wrapper"),
  question("func-006", "python-functions", "python-legb-name-resolution", "Junior", "اشرح قاعدة LEGB في حل الأسماء؟", "Python يبحث في Local ثم Enclosing ثم Global ثم Builtins.", "فهم LEGB يفسر closures وUnboundLocalError. قلّل تعديل global state، واستخدم parameters وreturn values أو object state بدل الاعتماد على أسماء بعيدة يصعب تتبعها.", "Python tutorial — Scopes and namespaces", "https://docs.python.org/3/tutorial/classes.html#python-scopes-and-namespaces"),
  question("func-007", "python-functions", "python-lambda-vs-def", "Junior", "إمتى تستخدم lambda وإمتى def؟", "lambda مناسبة لتعبير صغير inline، بينما def أفضل للمنطق المسمي أو القابل للاختبار والتوثيق.", "lambda لا تمنع التعقيد تقنيًا، لكنها تضعف القراءة والتتبع إذا احتوت أكثر من تحويل بسيط. اسم الدالة يوثق النية ويجعل stack traces أوضح.", "Python documentation — lambda expressions", "https://docs.python.org/3/reference/expressions.html#lambda"),
  question("func-008", "python-functions", "python-functools-partial", "Mid", "ما فائدة functools.partial؟", "تنشئ callable جديدًا يثبت بعض arguments لدالة موجودة.", "partial مفيد عند تمرير callback يحتاج سياقًا ثابتًا من غير lambda إضافية. راقب وضوح التوقيع والـrepr، ولا تستخدمه لبناء abstraction يخفي dependency مهمة.", "Python documentation — functools.partial", "https://docs.python.org/3/library/functools.html#functools.partial", "from functools import partial\nparse_port = partial(int, base=10)"),
  question("func-009", "python-functions", "python-recursion-and-stack-limit", "Mid", "إيه حدود recursion في Python وإمتى تختار loop؟", "recursion تستخدم stack frames ولها حد افتراضي، لذلك loop أو generator أنسب غالبًا للمسارات العميقة.", "لا ترفع recursion limit كحل أعمى؛ قد يؤدي ذلك إلى crash في C stack. استخدم recursion عندما تبسط traversal صغيرًا ومحدود العمق، وإلا حوّل الحالة إلى stack صريح.", "Python documentation — sys.setrecursionlimit", "https://docs.python.org/3/library/sys.html#sys.setrecursionlimit"),
  question("func-010", "python-functions", "python-first-class-functions-and-callbacks", "Junior", "ماذا يعني أن functions هي first-class objects؟", "يمكن إسناد function لمتغير وتمريرها وإعادتها وتخزينها مثل أي object آخر.", "هذا أساس callbacks وhigher-order functions وdecorators. اجعل callback contract واضحًا من حيث arguments والأخطاء، ولا تحول كل منطق إلى سلسلة callbacks يصعب تتبعها.", "Python tutorial — Defining functions", "https://docs.python.org/3/tutorial/controlflow.html#defining-functions"),

  // Typing
  question("type-001", "python-typing", "python-type-hints-runtime-vs-static-checking", "Junior", "هل type hints بتتفرض runtime في Python؟", "لا؛ annotations معلومات يمكن لأدوات static analysis قراءتها، لكنها لا تمنع runtime value من نوع مختلف تلقائيًا.", "استخدم type checker وtests للتحقق، وضع validation صريحًا عند حدود النظام مثل HTTP أو ملفات المستخدم. annotation ليست بديلًا عن فحص input غير الموثوق.", "Python documentation — typing support", "https://docs.python.org/3/library/typing.html"),
  question("type-002", "python-typing", "python-union-optional-types", "Junior", "إزاي تعبر عن قيمة قد تكون من نوعين أو None؟", "استخدم union مثل str | None في الإصدارات الحديثة، أو Union وOptional في الصيغ الأقدم.", "نوع None يجب أن يظهر في العقد بدل إخفائه داخل Any. بعد الفحص، يستطيع type checker تضييق النوع، لكن يجب أن يعكس الكود حالات الغياب بوضوح.", "Python documentation — typing.Optional", "https://docs.python.org/3/library/typing.html#typing.Optional", "def find_user(user_id: int) -> User | None:\n    ..."),
  question("type-003", "python-typing", "python-protocol-structural-typing", "Mid", "ما هو Protocol في typing؟", "Protocol يصف السلوك المطلوب بالـmethods والattributes ويسمح بـstructural typing بدون inheritance صريح.", "هو مناسب عندما تعتمد الدالة على capability مثل read أو close لا على class بعينه. حافظ على protocol صغير حتى لا تربط المستهلك بتفاصيل implementation.", "Python documentation — typing.Protocol", "https://docs.python.org/3/library/typing.html#typing.Protocol"),
  question("type-004", "python-typing", "python-typevar-generics", "Mid", "إيه دور TypeVar وGeneric؟", "TypeVar يمثل type ثابتًا عبر أجزاء signature، وGeneric يسمح بتعريف container أو service يحافظ على نوعه.", "الهدف هو أن تفهم الأداة العلاقة بين input وoutput، لا أن تضع أنواعًا معقدة لكل شيء. ابدأ بتوقيع بسيط، وأضف generic عندما يكون هناك contract قابل لإعادة الاستخدام.", "Python documentation — typing.TypeVar", "https://docs.python.org/3/library/typing.html#typing.TypeVar"),
  question("type-005", "python-typing", "python-typeddict-json-shapes", "Mid", "متى تستخدم TypedDict مع JSON؟", "TypedDict يصف مفاتيح dict المتوقعة لأدوات type checking من غير تحويله تلقائيًا إلى runtime object.", "هو ممتاز لوصف payload بعد أن تتحقق منه، لكنه لا يثبت أن JSON القادم من الشبكة صالح. اجمعه مع validation عند boundary ثم مرر نوعًا موثوقًا للداخل.", "Python documentation — typing.TypedDict", "https://docs.python.org/3/library/typing.html#typing.TypedDict"),
  question("type-006", "python-typing", "python-final-literal-and-constants", "Junior", "إيه استخدام Final وLiteral؟", "Final تشير إلى اسم لا يُعاد إسناده وفق أدوات الفحص، وLiteral يحصر القيمة في مجموعة literals معروفة.", "هذه annotations توثق configuration والخيارات المغلقة مثل environment أو status. لا تعتمد عليها للحماية من input خارجي قبل validation وقت التشغيل.", "Python documentation — typing.Final and Literal", "https://docs.python.org/3/library/typing.html#typing.Final"),
  question("type-007", "python-typing", "python-overload-public-api", "Senior", "متى تستخدم @overload؟", "تكتب به عدة signatures لتحسين static checking لواجهة واحدة، بينما يبقى implementation الفعلي signature عامة واحدة.", "overload لا ينشئ dispatch runtime. يجب أن يغطي implementation كل الحالات التي تصفها overloads، وأن يكون ترتيب الحالات منطقيًا حتى لا يعطي checker نتيجة مضللة.", "Python documentation — typing.overload", "https://docs.python.org/3/library/typing.html#typing.overload"),
  question("type-008", "python-typing", "python-any-vs-object", "Mid", "ما الفرق بين Any وobject؟", "Any يعطل جزءًا كبيرًا من فحص الأنواع، بينما object يقبل أي قيمة لكنه لا يسمح باستدعاء عمليات خاصة دون تضييق النوع.", "استخدم object عندما تحتاج boundary عامة مع الحفاظ على safety، وAny فقط عند تكامل لا يمكن وصفه أو migration مؤقتة. انتشار Any يجعل الأخطاء تظهر متأخرًا.", "Python documentation — typing.Any", "https://docs.python.org/3/library/typing.html#typing.Any"),
  question("type-009", "python-typing", "python-typeguard-narrowing", "Senior", "ما فائدة TypeGuard في type narrowing؟", "تعلن أن دالة predicate إذا أعادت True فقد ضيّقت النوع إلى نوع محدد لأداة type checker.", "TypeGuard يوثق علاقة الفحص بالنتيجة، لكنه لا ينفذ validation من تلقاء نفسه. يجب أن تكون predicate صحيحة وآمنة؛ annotation خاطئة قد تخفي bug بدل منعه.", "Python documentation — typing.TypeGuard", "https://docs.python.org/3/library/typing.html#typing.TypeGuard"),
  question("type-010", "python-typing", "python-annotations-interfaces-boundaries", "Senior", "إزاي تستخدم typing لتحسين حدود module من غير إفراط؟", "عرّف أنواع domain والـprotocols عند الحدود المهمة، واترك التفاصيل المحلية بسيطة.", "أفضل annotation هي التي توضح dependency أو invariant يستفيد منه القارئ والأداة. لا تحول كل local variable إلى puzzle من generics؛ قِس قيمة النوع مقابل كلفة القراءة والصيانة.", "PEP 484 — Type Hints", "https://peps.python.org/pep-0484/"),

  // Errors and resource safety
  question("error-001", "python-errors", "python-exception-hierarchy", "Junior", "إزاي تختار exception مناسب وتتعامل مع hierarchy؟", "ارمِ exception يعبر عن failure، والتقط أضيق نوع تستطيع التعامل معه بدل except Exception في كل مكان.", "الـhierarchy تسمح بتجميع حالات متشابهة مثل ValueError، لكن التقاط BaseException قد يبتلع KeyboardInterrupt وSystemExit. عالج الخطأ في layer التي تملك قرار التعافي أو التحويل.", "Python documentation — Built-in exceptions", "https://docs.python.org/3/library/exceptions.html"),
  question("error-002", "python-errors", "python-try-except-else-finally", "Junior", "ما الفرق بين except وelse وfinally؟", "except يعالج exception، else يعمل عند النجاح فقط، وfinally ينفذ بغض النظر عن النتيجة.", "ضع الكود الذي تريد حمايته داخل try بأضيق نطاق. else يمنع التقاط exception ناتج من success handling بالخطأ، وfinally مناسب للتنظيف لا لتحويل كل الأخطاء إلى نجاح.", "Python tutorial — Errors and exceptions", "https://docs.python.org/3/tutorial/errors.html", "try:\n    value = parse(text)\nexcept ValueError:\n    value = None\nelse:\n    audit(value)\nfinally:\n    close()"),
  question("error-003", "python-errors", "python-custom-exceptions", "Junior", "إمتى تعمل custom exception؟", "أنشئ exception عندما يحتاج المستهلك إلى التمييز بين failure domain معين واتخاذ قرار مختلف.", "اجعل الاسم والحقول يعبران عن السبب، وارث من Exception أو subclass domain مناسب. لا تنشئ class لكل رسالة نصية؛ القيمة تأتي من قابلية الالتقاط والبيانات المصاحبة.", "Python documentation — User-defined exceptions", "https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions"),
  question("error-004", "python-errors", "python-eafp-vs-lbyl", "Mid", "ما الفرق بين EAFP وLBYL؟", "EAFP يحاول العملية ويتعامل مع exception، وLBYL يفحص قبل المحاولة.", "EAFP طبيعي مع APIs التي قد تتغير بين الفحص والاستخدام، لكن exception يجب ألا يكون مسارًا متكررًا عاديًا عالي الكلفة. اختر بناءً على atomicity والوضوح، لا كقاعدة مطلقة.", "Python glossary — EAFP", "https://docs.python.org/3/glossary.html#term-eafp"),
  question("error-005", "python-errors", "python-exception-chaining-from", "Mid", "إيه فائدة raise ... from؟", "تربط exception عالي المستوى بالسبب الأصلي وتحافظ على سياق التشخيص.", "حوّل تفاصيل library إلى domain error عند boundary مع إبقاء السبب عبر chaining. استخدم from None فقط عندما يكون إخفاء السياق مقصودًا وواضحًا، وإلا ستصعّب debugging.", "Python documentation — The raise statement", "https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement", "try:\n    payload = decode(raw)\nexcept ValueError as error:\n    raise InvalidMessage() from error"),
  question("error-006", "python-errors", "python-contextlib-resource-cleanup", "Mid", "إزاي contextlib يساعد في إدارة الموارد؟", "يوفر أدوات مثل contextmanager وclosing وnullcontext لبناء أو تركيب cleanup واضح حول with.", "context manager يقلل تكرار try/finally ويضمن lifecycle. استخدمه للملفات والlocks والاتصالات، ولا تجعل generator context manager يخفي أكثر من setup وcleanup البسيط.", "Python documentation — contextlib", "https://docs.python.org/3/library/contextlib.html"),
  question("error-007", "python-errors", "python-logging-exception-context", "Mid", "إزاي تسجل exception من غير ما تخسر traceback؟", "استخدم logger.exception داخل except أو مرر exc_info=True بدل تسجيل message فقط.", "السجل يجب أن يحتوي context مفيدًا من غير أسرار أو tokens. اترك exception ينتشر إذا كانت layer الحالية لا تستطيع التعافي، وسجل مرة في boundary المناسبة بدل duplicate logs.", "Python documentation — logging", "https://docs.python.org/3/library/logging.html", "try:\n    process()\nexcept ValueError:\n    logger.exception(\"Invalid input\")\n    raise"),
  question("error-008", "python-errors", "python-timeouts-and-retry-boundaries", "Senior", "إزاي تصمم timeout وretry من غير ما تضاعف الضرر؟", "حدد timeout لكل عملية I/O، وأعد المحاولة فقط للأخطاء المؤقتة مع backoff وحد أقصى وشرط idempotency.", "retry بلا حد قد يحول failure إلى traffic storm. لا تعيد POST غير idempotent تلقائيًا، واحتفظ بالسياق والـdeadline عبر الطبقات بدل أن يضيف كل wrapper timeout جديدًا.", "Python documentation — asyncio timeouts", "https://docs.python.org/3/library/asyncio-task.html#timeouts"),
  question("error-009", "python-errors", "python-exceptiongroup-and-except-star", "Senior", "متى تحتاج ExceptionGroup وexcept*؟", "عندما تفشل مهام متوازية متعددة وتحتاج عرض أو معالجة أكثر من exception في وقت واحد.", "ExceptionGroup يحافظ على مجموعة failures بدل إسقاطها إلى أول خطأ فقط. استخدم except* لمعالجة أنواع متطابقة داخل المجموعة، ولا تستخدمه لمجرد تعقيد flow sequential.", "Python documentation — Exception groups", "https://docs.python.org/3/tutorial/errors.html#raising-and-handling-multiple-unrelated-exceptions"),
  question("error-010", "python-errors", "python-validation-at-trust-boundaries", "Mid", "أين يجب وضع validation للبيانات القادمة من خارج النظام؟", "عند boundary مثل HTTP أو CLI أو file parsing، ثم مرر model موثوقًا للداخل.", "التحقق المبكر يقلل تكرار defensive checks، لكن يجب التفريق بين malformed input وbusiness rule violation. أعد error قابلًا للفهم للمستخدم، وسجل التفاصيل الحساسة بحذر.", "Python documentation — json", "https://docs.python.org/3/library/json.html"),

  // Concurrency and async
  question("con-001", "python-concurrency", "python-gil-and-cpu-bound-work", "Mid", "إيه تأثير GIL في CPython؟", "في CPython التقليدي يمنع GIL تنفيذ bytecode Python بالتوازي داخل أكثر من thread في الوقت نفسه.", "هذا لا يجعل threads بلا فائدة؛ هي مناسبة لكثير من I/O لأن انتظار الشبكة يحرر التنفيذ. للأعمال CPU-bound استخدم multiprocessing أو native code مناسبًا، ثم قِس قبل القرار.", "Python FAQ — Global interpreter lock", "https://docs.python.org/3/faq/library.html#what-is-the-global-interpreter-lock"),
  question("con-002", "python-concurrency", "python-threading-vs-multiprocessing", "Mid", "إمتى تختار threading وإمتى multiprocessing؟", "threading مناسب لتداخل I/O ومشاركة ذاكرة أخف، وmultiprocessing يعزل الذاكرة ويمكنه تشغيل CPU work بالتوازي في CPython.", "processes تحتاج serialization وتكلفة إنشاء واتصال أكبر، بينما threads تشارك state وتحتاج synchronization. القرار يعتمد على طبيعة العمل وحجم البيانات وحدود التشغيل، لا على شعار واحد.", "Python documentation — multiprocessing", "https://docs.python.org/3/library/multiprocessing.html"),
  question("con-003", "python-concurrency", "python-asyncio-event-loop-coroutines", "Junior", "ما هو event loop وإيه دور coroutine؟", "event loop يدير awaitables ويشغل coroutine حتى نقطة await ثم يمرر التنفيذ لعمل جاهز.", "asyncio ممتاز لتعدد عمليات I/O غير المتزامنة داخل thread، لكنه لا يجعل كودًا CPU-heavy غير متزامنًا تلقائيًا. أي blocking call داخل coroutine قد يوقف كل المهام على loop.", "Python documentation — asyncio", "https://docs.python.org/3/library/asyncio.html", "async def fetch():\n    response = await client.get(url)\n    return response"),
  question("con-004", "python-concurrency", "python-task-future-coroutine", "Mid", "ما الفرق بين coroutine وTask وFuture في asyncio؟", "coroutine وصف لعمل async، وTask يجدول coroutine للتنفيذ، وFuture يمثل نتيجة ستكتمل لاحقًا.", "إنشاء coroutine وحده لا يشغلها. أنشئ Task عندما تريد concurrency أو إدارة lifecycle، وانتظر النتيجة أو احتفظ بالمرجع حتى لا تفقد exceptions.", "Python documentation — asyncio Tasks", "https://docs.python.org/3/library/asyncio-task.html"),
  question("con-005", "python-concurrency", "python-gather-taskgroup-failure-policy", "Senior", "إيه الفرق العملي بين gather وTaskGroup؟", "كلاهما يدير عدة awaitables، بينما TaskGroup يقدم structured concurrency ويلغي الأشقاء عند failure ويجمع الخروج بطريقة أوضح.", "اختر policy صريحة: هل كل النتائج مطلوبة، هل فشل واحدة يلغي الباقي، وكيف تُجمع الأخطاء؟ لا تطلق tasks بدون owner واضح لـwait وcancel.", "Python documentation — asyncio TaskGroup", "https://docs.python.org/3/library/asyncio-task.html#task-groups", "async with asyncio.TaskGroup() as group:\n    group.create_task(load_users())\n    group.create_task(load_settings())"),
  question("con-006", "python-concurrency", "python-cancellation-cooperative-cleanup", "Senior", "إزاي تتعامل مع cancellation في asyncio؟", "التنفيذ تعاوني؛ CancelledError تظهر عند نقاط await ويجب تنظيف الموارد ثم إعادة رفعها غالبًا.", "ابتلاع cancellation يجعل shutdown والتوقيتات عالقة. استخدم finally للتنظيف، وshield فقط لحماية جزء صغير له سبب قوي، مع إبقاء task قابلة للإلغاء بعده.", "Python documentation — asyncio task cancellation", "https://docs.python.org/3/library/asyncio-task.html#task-cancellation"),
  question("con-007", "python-concurrency", "python-run-in-executor-for-blocking-io", "Mid", "إزاي تشغل blocking function داخل asyncio؟", "مررها إلى asyncio.to_thread أو executor حتى لا تحجب event loop.", "هذا يحسن responsiveness لكنه لا يجعل CPU-bound Python parallel فعليًا بسبب GIL في threads. حدد pool وحجم العمل، ولا ترسل loop calls blocking بلا قياس.", "Python documentation — asyncio.to_thread", "https://docs.python.org/3/library/asyncio-task.html#asyncio.to_thread", "result = await asyncio.to_thread(read_large_file, path)"),
  question("con-008", "python-concurrency", "python-asyncio-queues-backpressure", "Senior", "ما دور asyncio.Queue في producer-consumer؟", "تفصل المنتج عن المستهلك وتتيح تحديد maxsize لفرض backpressure عندما يتراكم العمل.", "Queue محدودة تمنع الذاكرة من النمو بلا سقف، لكن يجب تعريف shutdown وacknowledgement وtimeout. لا تجعل المنتج ينتظر للأبد إذا توقف المستهلك.", "Python documentation — asyncio queues", "https://docs.python.org/3/library/asyncio-queue.html"),
  question("con-009", "python-concurrency", "python-lock-race-condition", "Mid", "متى تحتاج Lock في كود concurrent؟", "تحتاجه لحماية invariant مشترك من interleaving غير آمن بين المهام أو threads.", "القفل يعالج race لكنه قد يخفي تصميمًا يشارك state أكثر من اللازم. اجعل critical section قصيرة، واتفق على ترتيب locks، ولا تستخدم asyncio.Lock لحماية كود يعمل خارج نفس event loop.", "Python documentation — threading.Lock", "https://docs.python.org/3/library/threading.html#threading.Lock"),
  question("con-010", "python-concurrency", "python-concurrent-futures-map-shutdown", "Mid", "إيه فائدة concurrent.futures؟", "تقدم واجهة موحدة نسبيًا لإرسال work إلى ThreadPoolExecutor أو ProcessPoolExecutor ومتابعة Futures.", "حدّد طريقة إغلاق executor وتوقع exceptions داخل future. ProcessPool يتطلب أن تكون المدخلات والدالة قابلة للـpickle، لذلك لا تمرر closures أو objects غير قابلة للتسلسل بلا تحقق.", "Python documentation — concurrent.futures", "https://docs.python.org/3/library/concurrent.futures.html"),

  // Testing
  question("test-001", "python-testing", "python-unit-vs-integration-tests", "Junior", "ما الفرق بين unit وintegration tests؟", "unit تختبر وحدة صغيرة بعزل dependencies، وintegration تختبر تعاونًا حقيقيًا بين أكثر من boundary.", "ابدأ باختبارات domain سريعة، وأضف integration حيث يكون contract بين database أو HTTP أو filesystem هو مصدر الخطر. لا تحول كل test إلى end-to-end بطيء.", "Python documentation — unittest", "https://docs.python.org/3/library/unittest.html"),
  question("test-002", "python-testing", "python-pytest-fixtures-lifecycle", "Junior", "إيه دور fixtures في pytest؟", "تجهز dependency أو data للاختبار وتتحكم في lifecycle وإعادة الاستخدام.", "fixture الجيدة تعبر عن resource واحد وتغلقه بعد الاختبار عند الحاجة. تجنب fixture ضخمة تخفي setup كامل للتطبيق وتجعل كل test يعتمد على state غير واضح.", "pytest documentation — Fixtures", "https://docs.pytest.org/en/stable/explanation/fixtures.html"),
  question("test-003", "python-testing", "python-pytest-parametrize", "Junior", "إزاي تختبر حالات متعددة من غير تكرار؟", "استخدم parametrization لتشغيل نفس test على inputs وexpected results مختلفة.", "الحالات يجب أن تغطي boundary والفشل لا مجرد نسخ أمثلة متشابهة. سمِّ كل case أو اجعل ids واضحة حتى يكون failure قابلًا للفهم.", "pytest documentation — Parametrize", "https://docs.pytest.org/en/stable/how-to/parametrize.html", "@pytest.mark.parametrize(\"value, expected\", [(1, True), (0, False)])\ndef test_truth(value, expected):\n    assert bool(value) is expected"),
  question("test-004", "python-testing", "python-unittest-mock-patch-boundary", "Mid", "إزاي تستخدم mock وpatch بشكل صحيح؟", "patch يستبدل الاسم في المكان الذي يستخدمه الكود تحت الاختبار، وليس بالضرورة المكان الذي عُرّف فيه الأصل.", "mock يختبر interaction عندما تكون dependency خارجية أو غير حتمية، لكنه قد يثبت implementation أكثر من اللازم. فضّل fake صغير أو contract test عندما يكون ذلك أوضح.", "Python documentation — unittest.mock", "https://docs.python.org/3/library/unittest.mock.html"),
  question("test-005", "python-testing", "python-async-test-isolation", "Mid", "إزاي تختبر async code؟", "استخدم runner أو support مناسب مثل pytest-asyncio في المشروع، وانتظر coroutine فعليًا داخل الاختبار.", "اعزل network والوقت والـbackground tasks، وتحقق من cancellation والأخطاء. لا تنشئ event loop جديدًا عشوائيًا لكل helper بما يترك tasks معلقة.", "Python documentation — asyncio runners", "https://docs.python.org/3/library/asyncio-runner.html"),
  question("test-006", "python-testing", "python-testing-expected-exceptions", "Junior", "إزاي تثبت إن الدالة ترمي exception صحيح؟", "استخدم assertRaises في unittest أو pytest.raises مع النوع، ويفضل فحص الرسالة أو الحقول المهمة فقط.", "اختبر الحد الأدنى من العقد حتى لا يصبح test حساسًا لصياغة الرسالة. ضع الكود المتوقع فشله داخل context الاختبار، لا حول test كامل بلا داعٍ.", "Python documentation — unittest assertRaises", "https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises"),
  question("test-007", "python-testing", "python-deterministic-time-randomness-tests", "Mid", "إزاي تمنع الوقت والعشوائية من جعل الاختبارات flaky؟", "مرر clock أو random source كـdependency قابلة للاستبدال بدل قراءة global time/random مباشرة داخل domain logic.", "ثبّت seed عندما تحتاج reproducibility، لكن لا تعتبر seed علاجًا لكل nondeterminism. اختبر timezone والحدود الزمنية صراحة، واجعل cleanup مضمونًا.", "Python documentation — random", "https://docs.python.org/3/library/random.html"),
  question("test-008", "python-testing", "python-network-boundary-tests", "Mid", "إزاي تختبر كود HTTP من غير الاعتماد على شبكة حقيقية؟", "اختبر client عبر fake أو transport stub، ثم أضف عددًا محدودًا من contract/integration tests ضد service حقيقية.", "الشبكة الحقيقية تضيف latency وflakiness؛ fake يجب أن يمثل status وtimeouts وpayloads الفاشلة، لا أن يعيد نجاحًا دائمًا يخفي أخطاء التحويل.", "Python documentation — urllib.request", "https://docs.python.org/3/library/urllib.request.html"),
  question("test-009", "python-testing", "python-coverage-risk-based-testing", "Senior", "هل نسبة coverage العالية معناها كود مختبر جيد؟", "لا؛ coverage تقيس ما تم تنفيذه لا جودة assertions أو تغطية الحالات الخطرة.", "استخدمها كإشارة لا كهدف منفرد. راجع business invariants وfailure paths وintegration contracts، ثم اعمل coverage threshold فقط حيث يملك معنى صيانة حقيقي.", "coverage.py documentation — Measurement", "https://coverage.readthedocs.io/en/latest/"),
  question("test-010", "python-testing", "python-test-contracts-boundary", "Senior", "ما هو contract test وإمتى يفيد؟", "يثبت أن طرفين يتفقان على شكل وsemantics للبيانات أو الواجهة من غير اختبار كل implementation داخلي.", "هو مفيد بين service وclient أو adapter وrepository. اجعل العقد صغيرًا ومستقرًا، واحتفظ باختبارات integration تكشف اختلافات البيئة التي لا يغطيها contract وحده.", "Python documentation — doctest", "https://docs.python.org/3/library/doctest.html"),

  // Packaging and tooling
  question("pack-001", "python-packaging", "python-venv-isolated-environment", "Junior", "ليه نستخدم venv؟", "ينشئ بيئة معزولة لمكتبات المشروع حتى لا تتداخل مع Python أو dependencies لمشاريع أخرى.", "العزل يقلل اختلافات التشغيل لكنه لا يقفل versions وحده. أنشئ البيئة من requirements أو pyproject واضحة، ولا تضع مجلد البيئة داخل package المنشورة.", "Python documentation — venv", "https://docs.python.org/3/library/venv.html"),
  question("pack-002", "python-packaging", "python-pyproject-toml-build-metadata", "Mid", "ما دور pyproject.toml؟", "هو ملف قياسي لوصف build system وmetadata وأدوات المشروع مثل formatters وlinters.", "فصل metadata عن طريقة البناء يسمح لأدوات مختلفة بالتعاون. اجعل dependency declarations وproject metadata مصدرًا واضحًا واحدًا، ولا تخلط إعدادات runtime السرية في الملف المنشور.", "Python Packaging User Guide — pyproject.toml", "https://packaging.python.org/en/latest/guides/writing-pyproject-toml/"),
  question("pack-003", "python-packaging", "python-requirements-constraints-dependencies", "Mid", "ما الفرق بين requirements وconstraints؟", "requirements تحدد ما يحتاجه المشروع، بينما constraints تقيد versions المحلولة من غير أن تضيف dependency جديدة وحدها.", "استخدم constraints لتوحيد حل dependencies عبر تطبيقات أو بيئات، مع مراجعة التحديثات. لا تثبت كل شيء عشوائيًا من غير معرفة direct وtransitive dependencies.", "pip documentation — Constraints files", "https://pip.pypa.io/en/stable/user_guide/#constraints-files"),
  question("pack-004", "python-packaging", "python-package-src-layout", "Mid", "إيه فائدة src layout في package؟", "يمنع import العرضي من working directory ويجعل الاختبار أقرب إلى استهلاك package المثبتة.", "src layout يضيف خطوة تثبيت editable أثناء التطوير، لكنه يكشف أخطاء packaging التي قد يخفيها flat layout. اختره للمكتبات أو المشاريع التي تحتاج boundary نشر واضحة.", "Python Packaging User Guide — src layout", "https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/"),
  question("pack-005", "python-packaging", "python-editable-install-development", "Junior", "إيه معنى editable install؟", "يثبت metadata والروابط اللازمة بحيث تعكس تعديلات source فورًا أثناء التطوير بدل نسخ الملفات إلى site-packages.", "هو مناسب للتطوير وليس artifact للنشر. اختبر wheel أو sdist منفصلًا لأن نجاح editable install لا يضمن أن package المنشورة تحتوي كل الملفات.", "Python Packaging User Guide — Editable installs", "https://packaging.python.org/en/latest/topics/local-project-installs/#editable-installs"),
  question("pack-006", "python-packaging", "python-wheel-vs-sdist", "Mid", "ما الفرق بين wheel وsource distribution؟", "wheel artifact جاهز للتثبيت غالبًا، وsdist يحتوي المصدر وbuild metadata وقد يحتاج build وقت التثبيت.", "انشر artifacts قابلة لإعادة البناء وتحقق من محتواها. wheel تقلل build cost للمستخدم، لكن بعض المشاريع تحتاج native build لكل منصة.", "Python Packaging User Guide — Packaging binary extensions", "https://packaging.python.org/en/latest/guides/packaging-binary-extensions/"),
  question("pack-007", "python-packaging", "python-console-script-entry-point", "Mid", "إزاي تعرض CLI command من package؟", "عرّف console script entry point في project metadata ليشير إلى دالة main قابلة للاستدعاء.", "الـentry point يفصل اسم الأمر عن path الداخلي ويضمن setup موحدًا. اجعل main تعيد exit code أو تستخدم argparse، ولا تنفذ CLI عند import.", "Python Packaging User Guide — Creating and discovering plugins", "https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/"),
  question("pack-008", "python-packaging", "python-version-constraints-and-support", "Mid", "إزاي تحدد إصدارات Python المدعومة؟", "أعلن requires-python وقيود dependencies، ثم اختبر الحد الأدنى والأعلى المقصودين في CI.", "تحديد الدعم دون اختبار يخلق وعدًا غير صحيح. فرّق بين language syntax وruntime APIs، وحدث matrix عندما تنتهي دورة دعم إصدار.", "Python Packaging User Guide — Declaring project metadata", "https://packaging.python.org/en/latest/specifications/declaring-project-metadata/"),
  question("pack-009", "python-packaging", "python-logging-configuration-deployment", "Mid", "إزاي تضبط logging في package أو service من غير ما تزعج المستهلك؟", "المكتبة تنشئ logger باسمها وتترك configuration للتطبيق، بينما التطبيق يحدد handlers وlevels.", "لا تضف StreamHandler أو basicConfig داخل library import. استخدم NullHandler للمكتبات عند الحاجة، وضمّن correlation context في الخدمة بدل طباعة أسرار أو بيانات شخصية.", "Python documentation — Logging HOWTO", "https://docs.python.org/3/howto/logging.html"),
  question("pack-010", "python-packaging", "python-environment-configuration-secrets", "Senior", "إزاي تفصل configuration عن secrets في تطبيق Python؟", "اقرأ configuration من environment أو secret manager عند boundary، ومرر قيمًا typed إلى التطبيق؛ لا تضع secrets في source أو package metadata.", "افصل defaults غير الحساسة عن credentials، تحقق من القيم عند بدء التشغيل، واجعل فشل secret المفقود واضحًا. لا تسجل قيمة environment لمجرد debugging.", "Python documentation — os.environ", "https://docs.python.org/3/library/os.html#os.environ"),

  // Performance
  question("perf-001", "python-performance", "python-measure-before-optimizing", "Junior", "ليه لازم نقيس قبل optimization؟", "لأن bottleneck الحقيقي قد لا يكون المكان المتوقع، والتحسين بلا قياس قد يزيد التعقيد دون أثر.", "ابدأ بوقت واقعي وdataset representative، حدد metric مثل latency أو memory، ثم قارن قبل وبعد بنفس الظروف. لا تستبدل readability بتحسين نظري غير مؤثر.", "Python documentation — timeit", "https://docs.python.org/3/library/timeit.html"),
  question("perf-002", "python-performance", "python-cprofile-hot-paths", "Mid", "إيه دور cProfile؟", "يسجل إحصاءات استدعاءات الدوال لمساعدتك في تحديد hot paths والوقت التراكمي.", "profile سيناريو حقيقيًا ثم اقرأ cumulative وown time. profiler يصف مكان الوقت، لكنه لا يثبت أن تغييرًا آمن أو أن I/O الخارجي تحسن؛ أعد القياس بعد التعديل.", "Python documentation — cProfile", "https://docs.python.org/3/library/profile.html"),
  question("perf-003", "python-performance", "python-list-vs-deque-queue-operations", "Mid", "إمتى تستخدم deque بدل list؟", "deque مناسب لإضافة وإزالة من الطرفين بكفاءة، بينما list مناسب للفهرسة والعمليات على مصفوفة متجاورة.", "لا تستخدم list.pop(0) في queue كبيرة لأنه يحرك بقية العناصر. اختر البنية حسب العمليات الأساسية، لا حسب familiarity فقط.", "Python documentation — collections.deque", "https://docs.python.org/3/library/collections.html#collections.deque"),
  question("perf-004", "python-performance", "python-generators-memory-tradeoff", "Junior", "متى generator يحسن الذاكرة ومتى لا يحسن latency؟", "يقلل peak memory بإنتاج العناصر عند الطلب، لكنه قد يضيف overhead لكل خطوة ولا يوفر نتائج جاهزة لإعادة الاستخدام.", "generator مناسب للـstreaming، لكن لو ستكرر المرور عدة مرات أو تحتاج random access فقد تكون list أسرع إجمالًا. قِس latency وmemory معًا.", "Python documentation — Generator expressions", "https://docs.python.org/3/reference/expressions.html#generator-expressions"),
  question("perf-005", "python-performance", "python-lru-cache-pure-functions", "Mid", "إزاي تستخدم lru_cache بأمان؟", "تخزن نتائج دالة حسب arguments حتى حد أقصى، وتناسب الدوال النقية ذات keys قابلة للـhash.", "الكاش لا يصلح لنتيجة تعتمد على الوقت أو المستخدم أو external state بلا invalidation. اختر maxsize وراقب hit rate، واحذر الاحتفاظ بأشياء كبيرة أو حساسة.", "Python documentation — functools.lru_cache", "https://docs.python.org/3/library/functools.html#functools.lru_cache", "from functools import lru_cache\n\n@lru_cache(maxsize=128)\ndef fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)"),
  question("perf-006", "python-performance", "python-string-join-vs-concatenation", "Junior", "ليه ''.join أفضل غالبًا لتجميع strings؟", "join يجمع iterable في عملية أوضح وأكفأ عادةً من concatenation متكرر داخل loop.", "الأهم هو وضوح boundary والتأكد أن العناصر strings. لا تعمل micro-optimization على جملة صغيرة؛ الفرق يظهر مع عدد كبير من الأجزاء.", "Python documentation — str.join", "https://docs.python.org/3/library/stdtypes.html#str.join"),
  question("perf-007", "python-performance", "python-sqlite-batch-transactions", "Mid", "إزاي تقلل كلفة إدخال rows كثيرة في SQLite؟", "اجمع الإدخالات في transaction واحدة واستخدم executemany بدل commit لكل row.", "كل commit قد يفرض sync وoverhead كبير. حافظ على transaction bounded، وتعامل مع rollback عند الفشل، ولا تضحي بسلامة atomicity من أجل benchmark صغير.", "Python documentation — sqlite3", "https://docs.python.org/3/library/sqlite3.html"),
  question("perf-008", "python-performance", "python-object-allocation-hot-loop", "Senior", "إزاي تتعامل مع كثرة object allocations في hot loop؟", "قِس أولًا، ثم قلل إنشاء objects غير الضرورية أو استخدم iterator أو local bindings عندما يثبت profiler أن ذلك bottleneck.", "تحسين allocation قد يضر القراءة أو يسبب state sharing أخطر. ركز على algorithm وI/O قبل micro-optimizations، واختبر memory behavior لا الزمن فقط.", "Python documentation — tracemalloc", "https://docs.python.org/3/library/tracemalloc.html"),
  question("perf-009", "python-performance", "python-memory-profiling-tracemalloc", "Mid", "إيه الذي يقيسه tracemalloc؟", "يتتبع allocations الخاصة بذاكرة Python ويعرض snapshots ومقارنات لمواضع الحجز.", "هو لا يقيس كل ذاكرة process من native extensions أو allocator بنفس الصورة. استخدمه لمقارنة نمو Python allocations مع سيناريو ثابت، ثم افحص resource owner الحقيقي.", "Python documentation — tracemalloc", "https://docs.python.org/3/library/tracemalloc.html"),
  question("perf-010", "python-performance", "python-algorithm-complexity-data-structures", "Senior", "إزاي اختيار data structure يغير performance؟", "التعقيد والعمليات المدعومة أهم من اسم اللغة؛ membership في set أو dict يختلف عن البحث الخطي في list.", "حلل عدد العناصر وتوزيع العمليات قبل التحسين. set وdict يحتاجان hashable keys وقد يستهلكان ذاكرة أكثر، لذلك القرار trade-off بين time وspace وordering.", "Python Wiki — TimeComplexity", "https://wiki.python.org/moin/TimeComplexity"),

  // Web, APIs, and data integration
  question("web-001", "python-web-data", "python-json-serialization-boundaries", "Junior", "إزاي تتعامل مع JSON القادم من API؟", "حوّل النص إلى Python values، تحقق من الشكل والأنواع عند boundary، ثم مرره إلى model أو domain structure موثوق.", "json.loads لا يضمن schema ولا business rules. افصل parsing عن validation وعن domain mapping، وارجع error يميز malformed JSON عن payload ناقص.", "Python documentation — json", "https://docs.python.org/3/library/json.html", "payload = json.loads(body)\nif not isinstance(payload, dict):\n    raise ValueError(\"Expected object\")"),
  question("web-002", "python-web-data", "python-url-parse-and-query-parameters", "Junior", "ليه تستخدم urllib.parse بدل تركيب URL بالـstring؟", "توفر APIs لفصل الأجزاء وترميز query parameters بأمان.", "تركيب URL يدويًا قد يكسر escaping أو يكرر ? و&. استخدم urlencode للمدخلات القادمة من المستخدم ولا تضع secrets في URL إذا كان header مناسبًا.", "Python documentation — urllib.parse", "https://docs.python.org/3/library/urllib.parse.html"),
  question("web-003", "python-web-data", "python-http-timeouts-and-status-handling", "Mid", "إيه قواعد HTTP client الأساسية في Python؟", "حدد timeout، افحص status code، أغلق response، وتعامل مع transport errors منفصلة عن أخطاء HTTP.", "نجاح الاتصال لا يعني نجاح الطلب. ميّز retryable statuses، لا تسجل authorization headers، واستخدم session/connection reuse عندما يدعم client ذلك.", "Python documentation — urllib.request", "https://docs.python.org/3/library/urllib.request.html"),
  question("web-004", "python-web-data", "python-sqlite-parameterized-queries", "Junior", "إزاي تمنع SQL injection مع sqlite3؟", "استخدم parameterized queries ولا تدخل input في SQL string بالـconcatenation.", "الـparameters تفصل code عن data. لا تعتبر escaping اليدوي بديلًا، وطبّق authorization وvalidation على مستوى domain أيضًا.", "Python documentation — sqlite3 placeholders", "https://docs.python.org/3/library/sqlite3.html#sqlite3-placeholders", "cursor.execute(\"SELECT * FROM users WHERE id = ?\", (user_id,))"),
  question("web-005", "python-web-data", "python-sqlite-transaction-commit-rollback", "Mid", "إزاي تدير transaction في sqlite3؟", "نفذ مجموعة تغييرات كوحدة atomic، ثم commit عند النجاح أو rollback عند failure.", "حدد حدود transaction صغيرة بما يكفي، ولا تترك connection مفتوحة بلا إدارة. transaction ليست بديلًا عن idempotency عند إعادة الطلب من شبكة.", "Python documentation — sqlite3 transaction control", "https://docs.python.org/3/library/sqlite3.html#transaction-control"),
  question("web-006", "python-web-data", "python-csv-dialect-and-newline", "Junior", "إزاي تقرأ وتكتب CSV بشكل portable؟", "استخدم csv module مع newline=''، واترك dialect أو quoting يحدد شكل الملف بدل split(',') اليدوي.", "CSV ليس مجرد comma split؛ quoting وnewlines وencoding تغير parsing. تعامل مع headers وmissing fields صراحة، ولا تثق في formula-like values عند فتحها في spreadsheet.", "Python documentation — csv", "https://docs.python.org/3/library/csv.html", "with open(path, newline=\"\", encoding=\"utf-8\") as handle:\n    rows = csv.DictReader(handle)"),
  question("web-007", "python-web-data", "python-datetime-timezone-aware-values", "Mid", "إيه مشكلة naive datetime في services؟", "لا تحتوي على timezone واضح، فتسبب مقارنة أو تحويلات خاطئة بين مناطق زمنية مختلفة.", "خزن instant بتمثيل timezone-aware أو UTC، وحوّل إلى timezone المستخدم عند العرض. اختبر DST والحدود، ولا تعتمد على local machine timezone بالصدفة.", "Python documentation — datetime", "https://docs.python.org/3/library/datetime.html"),
  question("web-008", "python-web-data", "python-pagination-cursors-and-consistency", "Senior", "إزاي تصمم pagination لـAPI؟", "اختر page/offset للبساطة أو cursor ثابتًا للبيانات الكبيرة والمتغيرة، وحدد ordering وnext token بوضوح.", "offset قد يتخطى أو يكرر rows إذا تغيرت البيانات أثناء التصفح. cursor يحتاج key ترتيب deterministic ويفضل ألا يكشف معلومات داخلية أو قابلة للتلاعب.", "RFC 8288 — Web Linking", "https://www.rfc-editor.org/rfc/rfc8288"),
  question("web-009", "python-web-data", "python-idempotency-retry-safe-writes", "Senior", "إزاي تمنع retry من إنشاء duplicate write؟", "استخدم idempotency key أو operation identifier محفوظًا مع نتيجة العملية، مع contract يحدد ما يحدث عند إعادة نفس الطلب.", "timeout لا يعني أن الخادم لم ينفذ؛ لذلك client قد يعيد المحاولة بعد نجاح غير مرئي. صمم write endpoint والسياسة التخزينية معًا، ولا تعتمد على client memory وحدها.", "RFC 9110 — HTTP Semantics", "https://www.rfc-editor.org/rfc/rfc9110"),
  question("web-010", "python-web-data", "python-payload-validation-and-domain-model", "Senior", "إزاي تفصل API schema عن domain model؟", "حوّل payload الخارجي إلى model داخلي بعد validation، ولا تجعل شكل JSON يحدد كل domain decisions.", "الفصل يمنع تسرب أسماء API وتغيراتها إلى core logic، ويسمح بإرجاع serialization مختلفة. احتفظ برسائل validation مفيدة، ورفض الحقول غير المتوقعة إذا كان ذلك جزءًا من security contract.", "Python documentation — dataclasses", "https://docs.python.org/3/library/dataclasses.html"),
];
