import { topicTranslations, type Locale } from "./content/questions.ts";
export type { Locale } from "./content/questions.ts";

export const locales: Locale[] = ["ar", "en"];
export const localeStorageKey = "jahezdev-locale";

export const messages = {
  ar: {
    submitDifficultyNone: "غير محدد", submitTrackPreference: "اختر مسارًا نشطًا من تفضيلات المسارات.",
    brandName: "JahezDev",
    home: "الرئيسية", topics: "الموضوعات", questions: "مكتبة الأسئلة", interview: "مقابلة كاملة", progress: "تقدمي", submit: "اقترح سؤالًا", moderator: "المراجعة", myTracks: "مساراتي", account: "الحساب",
    skip: "انتقل إلى المحتوى", menu: "القائمة", close: "إغلاق", theme: "تغيير المظهر", dark: "◐ الوضع الداكن", light: "☀ الوضع الفاتح", signIn: "تسجيل الدخول", signUp: "إنشاء حساب",
    libraryEyebrow: "مكتبة الأسئلة", libraryTitle: "مكتبة الأسئلة", libraryDescription: "راجع السؤال، جاوب بصوتك، وبعدها افتح التفاصيل وقارن إجابتك بشرح مدعوم بالمصدر الرسمي.",
    activeTrack: "المسار النشط", activeTrackLoading: "جاري تحميل المسار النشط…", activeTrackUnavailable: "تعذر تحميل المسار النشط", manageTrackPreferences: "إدارة تفضيلات المسارات", invalidTrackTitle: "المسار غير متاح", invalidTrackTopicTitle: "الموضوع لا ينتمي إلى هذا المسار", invalidTrackDescription: "غيّر المسار مع الحفاظ على سياق الصفحة، أو عدّل تفضيلات مساراتك.", changeTrackTo: "التغيير إلى", emptyTrackTitle: "لا يوجد محتوى في هذا المسار حاليًا", emptyTrackDescription: "المسار ما زال محددًا. اختر مسارًا آخر أو أدِر تفضيلاتك من غير تغيير صامت.",
    search: "ابحث في الأسئلة", searchPlaceholder: "مثال: final أو وقت التشغيل", topic: "الموضوع", allTopics: "كل الموضوعات", difficulty: "مستوى الصعوبة", allDifficulties: "كل المستويات", progressFilter: "حالة المراجعة", allProgress: "كل الحالات", favoriteOnly: "المفضلة فقط", sort: "الترتيب", defaultSort: "الترتيب الأساسي", mostAsked: "الأكثر سؤالًا", available: "سؤال متاح.", startSession: "ابدأ جلسة المراجعة", prepareSession: "جهّز جلسة مراجعة", noResults: "مفيش نتائج مطابقة", expandFilters: "جرّب تغيّر البحث أو توسّع الفلاتر.", communityScope: "أسئلة المجتمع", publicScope: "الأسئلة العامة", contributor: "بواسطة", likes: "إعجاب", promoted: "تمت الترقية تلقائيًا", like: "أعجبني", unlike: "إلغاء الإعجاب", signInToLike: "سجّل الدخول للإعجاب", communityLoadError: "تعذر تحميل أسئلة المجتمع حاليًا.", askedMarker: "سُئل في مقابلاتك", interviewFrequency: "تكرار السؤال", increaseAsked: "زيادة مرات السؤال", decreaseAsked: "تقليل مرات السؤال", signInToMarkAsked: "سجّل الدخول لتعديل العداد", askedMarkerUnavailable: "تعذر تحميل عداد السؤال حاليًا.",
    topicsEyebrow: "المسار النشط", topicsTitle: "الموضوعات", topicsDescription: "محتوى المسار النشط متقسم حسب المفاهيم اللي بتتقابل في الانترفيو.", availableQuestions: "سؤال متاح للمراجعة حاليًا.", viewQuestions: "عرض الأسئلة ←",
    homeEyebrow: "منصة تحضير المقابلات التقنية", homeTitle: "ادخل الانترفيو وإجابتك مرتبة في دماغك.", homeLead: "أسئلة تقنية مختارة، إجابات عربية واضحة، ومراجع رسمية تساعدك تراجع المفهوم بدل ما تحفظ جملة.", startReview: "ابدأ المراجعة", exploreTopics: "استكشف الموضوعات", totalQuestions: "إجمالي الأسئلة", currentQuestions: "سؤال دائم في النسخة الأولى", usersCount: "مستخدم مسجل", visitsCount: "إجمالي الزيارات", firstTopic: "أول موضوع متاح ضمن المسار النشط.", featuredTitle: "سؤال للمراجعة السريعة", featuredLead: "إجابة قصيرة أولاً، ثم شرح أعمق ومصدر رسمي.", allQuestions: "كل الأسئلة", answerPrompt: "جاوب من ذاكرتك، وبعدها اكشف الإجابة وقارن شرحك بالتفاصيل.", readAnswer: "اقرأ الإجابة كاملة ←",
    exploreAllTracks: "استكشف كافة المسارات التقنية", exploreAllTracksLead: "اختَر التخصص الذي تستعد له، وشاهد موضوعاته وأسئلته في مكان واحد.", chooseTrack: "ابدأ بهذا المسار", currentTrack: "المسار الحالي", switchTrack: "تحديد هذا المسار", trackQuestions: "سؤال", trackTopics: "موضوعًا", whyPrepareHere: "كيف تساعدك المنصة في اجتياز المقابلة؟", whyPrepareHereLead: "من الفهم إلى المحاكاة، كل خطوة مصممة لتذاكر بتركيز وتعرف مستواك الحقيقي.", feature1Title: "افهم الفكرة من مصدرها", feature1Lead: "إجابة مختصرة وشرح واضح، مع روابط للمراجع الرسمية لتثبّت المفهوم بدل ما تحفظه.", feature2Title: "تدرّب كأنها مقابلة حقيقية", feature2Lead: "كوّن مقابلة كاملة من موضوعات ومستوى يناسب هدفك، وشوف جاهزيتك قبل يوم المقابلة.", feature3Title: "راجع على طريقتك", feature3Lead: "اختبر نفسك سؤالًا بسؤال، اكشف الإجابة وقت ما تحتاجها، وراجع من غير ضغط مؤقت.", feature4Title: "شوف تقدّمك بوضوح", feature4Lead: "احفظ الأسئلة المهمة وتابع ما أتقنته على جهازك، مع مزامنة اختيارية وآمنة عند تسجيل الدخول.",
    sessionEyebrow: "جلسة مراجعة", sessionTitle: "جلسة مراجعة", sessionDescription: "اختار موضوعًا ومستوى، وراجع بالترتيب من غير مؤقت أو عشوائية.", chooseTopic: "اختار موضوعًا", chooseDifficulty: "اختار المستوى", preparing: "جاري تجهيز الجلسة...", question: "سؤال", of: "من", previous: "السؤال السابق", next: "السؤال التالي", noCombination: "لا توجد أسئلة للجمع ده", startStudy: "ابدأ جلسة مراجعة", selectSession: "اختار موضوعًا ومستوى من القوائم عشان نجهز لك الأسئلة بالترتيب.",
    interviewEyebrow: "مقابلة كاملة", interviewTitle: "ابنِ انترفيو شامل", interviewDescription: "اختار أكثر من موضوع من المسار النشط ومستوى واحد. المستوى الأعلى يشمل أسئلته وأسئلة المستويات الأقل.", chooseTopics: "اختار الموضوعات", selected: "مختارة", interviewLevel: "مستوى المقابلة", inclusiveHint: "المستوى المختار يشمل كل المستويات الأقل منه.", preparingInterview: "جاري تجهيز المقابلة...", completeSetup: "كمّل إعداد المقابلة", startInterview: "ابدأ مقابلة كاملة", interviewEmpty: "اختار موضوعًا واحدًا على الأقل ومستوى المقابلة عشان نجهز لك الأسئلة.",
    progressEyebrow: "تقدمك على حسابك", progressTitle: "تقدمي", progressDescription: "سجّل الدخول لحفظ تقدمك ومتابعته مع المسار الذي تختاره.", progressSignIn: "سجّل الدخول لمتابعة تقدّمك عبر أجهزتك.", progressAuthSetup: "تسجيل الدخول غير مفعّل في هذه البيئة.", reviewed: "راجعت", continueReview: "كمّل المراجعة", reviewing: "قيد المراجعة", mastered: "متقن", favorites: "المفضلة", noQuestions: "لا توجد أسئلة هنا حاليًا.", resetTitle: "إعادة ضبط البيانات المحلية", resetDescription: "يمسح تقدم الأسئلة والمفضلة فقط.", reset: "إعادة ضبط التقدم", resetConfirm: "متأكد إنك عايز تمسح تقدمك والمفضلة من الجهاز ده؟",
    backLibrary: "← مكتبة الأسئلة", lastReviewed: "آخر مراجعة", staleReview: "راجع الإجابة من المصدر قبل الانترفيو لو مر وقت طويل على التاريخ ده.", progressLegend: "تقدم السؤال", favorite: "حفظ في المفضلة", saved: "تم حفظ التقدم على هذا الجهاز", reveal: "اكشف الإجابة", hide: "اخفِ الإجابة", shortAnswer: "الإجابة المختصرة", explanation: "الشرح", code: "مثال بالكود", mistakes: "أخطاء شائعة", followUps: "أسئلة متابعة", sources: "المصادر", notFound: "السؤال غير موجود", databaseQuestionEyebrow: "سؤال من قاعدة البيانات", databaseQuestionLoading: "جاري تحميل السؤال…", databaseQuestionNotFound: "تأكد من الرابط أو ارجع لمكتبة الأسئلة.", databaseQuestionError: "تعذر تحميل السؤال", databaseQuestionErrorDescription: "حصلت مشكلة مؤقتة في الاتصال. جرّب مرة أخرى.", databaseQuestionRetry: "إعادة المحاولة", footer: "محتوى عربي أصلي بمراجع رسمية.", footerExplore: "استكشف", footerPractice: "تدرّب", footerPolicies: "السياسات", privacyPolicy: "سياسة الخصوصية", termsOfUse: "شروط الاستخدام", sourceCode: "المشروع على GitHub", footerNote: "محتوى تعليمي عام، وليس استشارة قانونية.", footerRights: "© 2026 JahezDev · بعض المحتوى مرخّص CC BY 4.0.", language: "English",
    submitEyebrow: "مساهمة المجتمع", submitTitle: "اقترح سؤال مقابلة", submitDescription: "شارك سؤالًا وإجابة مفيدة. كل مساهمة تمر بمراجعة قبل ظهورها في المكتبة.", submitLoading: "جاري تحميل حالة الحساب…", submitSignInRequired: "سجّل الدخول لإرسال سؤال.", submitTrack: "المسار", submitTopics: "الموضوعات", submitQuestion: "السؤال", submitShortAnswer: "الإجابة المختصرة", submitExplanation: "الشرح", submitDifficulty: "مستوى الصعوبة", submitSources: "مصادر رسمية", submitSourcesHint: "رابط HTTPS واحد في كل سطر", submitCode: "مثال بالكود (اختياري)", submitMistakes: "أخطاء شائعة (اختياري، كل سطر نقطة)", submitFollowups: "أسئلة متابعة (اختياري، كل سطر سؤال)", submitDisplayName: "اسم المستخدم الظاهر", submitConsent: "أوافق على نشر المساهمة بترخيص CC BY 4.0.", submitButton: "إرسال للمراجعة", submitSubmitting: "جاري الإرسال…", submitPending: "تم حفظ المساهمة وجاري إنشاء Issue للمراجعة…", submitSuccess: "تم إرسال المساهمة للمراجعة.", submitSuccessIssue: "فتح Issue على GitHub", submitDuplicate: "قد تكون مشابهة لسؤال موجود وسيُراجعها المشرف", submitFailed: "تعذر إنشاء Issue، يمكنك المحاولة مرة أخرى.", submitRetry: "إعادة المحاولة", submitRateLimit: "وصلت للحد اليومي (5 مساهمات).", submitCooldown: "انتظر دقيقة قبل إرسال مساهمة أخرى.", submitSuspended: "تم إيقاف حسابك مؤقتًا عن إرسال المساهمات.", submitValidation: "راجع الحقول المطلوبة، الروابط، والمحتوى قبل الإرسال.", submitUnavailable: "الخدمة غير متاحة حاليًا. حاول لاحقًا.", moderatorLoading: "جاري تحميل المساهمات…", moderatorSignIn: "سجّل الدخول للوصول إلى لوحة المراجعة.", moderatorStatus: "حالة المساهمات", moderatorRefresh: "تحديث", moderatorEmpty: "لا توجد مساهمات في هذه الحالة.", moderatorReason: "سبب القرار", moderatorChanges: "طلب تعديل", moderatorReject: "رفض المساهمة",
    onboardingEyebrow: "إعداد الحساب", onboardingTitle: "اختر مساراتك", onboardingDescription: "اختر مسارًا نشطًا واحدًا على الأقل وحدد المسار الافتراضي الذي تبدأ منه.", myTracksTitle: "مساراتي", myTracksDescription: "أضف أو احذف تفضيلات المسارات النشطة وغيّر المسار الافتراضي. لن يتأثر تقدم الأسئلة أو المفضلة أو المساهمات السابقة.", tracksLoading: "جاري تحميل المسارات…", tracksSignIn: "سجّل الدخول لإدارة مساراتك.", tracksAuthSetup: "إدارة المسارات تحتاج إعداد تسجيل الدخول أولًا.", tracksLegend: "تفضيلات المسارات", defaultTrackLegend: "المسار الافتراضي", defaultTrackHint: "يجب أن يكون المسار الافتراضي ضمن المسارات المختارة.", unavailableTracksLegend: "المسارات التاريخية غير المتاحة", trackUnavailable: "غير متاح", tracksRequired: "اختر مسارًا نشطًا واحدًا على الأقل.", defaultTrackRequired: "اختر مسارًا افتراضيًا من المسارات المختارة.", lastTrackRequired: "لا يمكن حذف آخر تفضيل مسار نشط.", tracksSave: "حفظ المسارات", tracksSaving: "جاري الحفظ…", tracksSaved: "تم حفظ تفضيلات المسارات والمسار الافتراضي.", tracksUnavailable: "تعذر تحميل أو حفظ تفضيلات المسارات. جرّب مرة أخرى.", tracksRetry: "إعادة المحاولة", tracksContinue: "متابعة", continueBrowsing: "متابعة تصفح المكتبة", noActiveTracksTitle: "لا توجد مسارات نشطة الآن", noActiveTracksDescription: "ارجع لاحقًا عندما يتوفر مسار نشط لإكمال الإعداد.", tracksRecoveryTitle: "المسارات المختارة لم تعد متاحة", tracksRecoveryDescription: "اختر مسارًا نشطًا جديدًا للعودة إلى الإعداد. بيانات تقدمك ومفضلاتك ومساهماتك السابقة محفوظة.", tracksRecoveryAction: "العودة إلى الإعداد",
  },
  en: {
    submitDifficultyNone: "Not specified", submitTrackPreference: "Choose one active Track Preference.",
    brandName: "JahezDev",
    home: "Home", topics: "Topics", questions: "Question Library", interview: "Full Interview", progress: "Progress", submit: "Suggest a question", moderator: "Moderation", myTracks: "My Tracks", account: "Account",
    skip: "Skip to content", menu: "Menu", close: "Close", theme: "Change theme", dark: "◐ Dark mode", light: "☀ Light mode", signIn: "Sign in", signUp: "Sign up",
    libraryEyebrow: "Question library", libraryTitle: "Question library", libraryDescription: "Answer out loud, open the details, and compare your reasoning with an answer backed by official sources.",
    activeTrack: "Active Track", activeTrackLoading: "Loading Active Track…", activeTrackUnavailable: "Active Track could not be loaded", manageTrackPreferences: "Manage Track Preferences", invalidTrackTitle: "This Track is unavailable", invalidTrackTopicTitle: "This Topic does not belong to the Active Track", invalidTrackDescription: "Change Track while keeping this page context, or manage your Track Preferences.", changeTrackTo: "Change to", emptyTrackTitle: "This Track has no content yet", emptyTrackDescription: "The Track remains selected. Choose another Track or manage preferences without a silent switch.",
    search: "Search questions", searchPlaceholder: "Example: final or runtime", topic: "Topic", allTopics: "All topics", difficulty: "Difficulty", allDifficulties: "All levels", progressFilter: "Question progress", allProgress: "All progress", favoriteOnly: "Favorites only", sort: "Sort", defaultSort: "Default order", mostAsked: "Most asked", available: "questions available.", startSession: "Start review session", prepareSession: "Prepare a review session", noResults: "No matching results", expandFilters: "Try changing the search or widening the filters.", communityScope: "Community questions", publicScope: "Public questions", contributor: "By", likes: "likes", promoted: "Automatically promoted", like: "Like", unlike: "Unlike", signInToLike: "Sign in to like", communityLoadError: "Community questions are temporarily unavailable.", askedMarker: "Asked in your interviews", interviewFrequency: "Interview frequency", increaseAsked: "Increase asked count", decreaseAsked: "Decrease asked count", signInToMarkAsked: "Sign in to change the count", askedMarkerUnavailable: "The question count is temporarily unavailable.",
    topicsEyebrow: "Active Track", topicsTitle: "Topics", topicsDescription: "Browse the interview concepts in the Active Track.", availableQuestions: "questions currently available for review.", viewQuestions: "View questions →",
    homeEyebrow: "Tech Interview Preparation Platform", homeTitle: "Walk into the interview with your answers organized.", homeLead: "Curated technical questions, clear explanations, and official references that help you understand instead of memorizing.", startReview: "Start reviewing", exploreTopics: "Explore topics", totalQuestions: "total questions", currentQuestions: "questions in the first release", usersCount: "registered users", visitsCount: "total visits", firstTopic: "First topic in the active track.", featuredTitle: "Quick Review Question", featuredLead: "A short answer first, then a deeper explanation and an official source.", allQuestions: "All questions", answerPrompt: "Answer from memory, then reveal the explanation and compare your reasoning.", readAnswer: "Read the full answer →",
    exploreAllTracks: "Explore All Tech Tracks", exploreAllTracksLead: "Choose the specialty you are preparing for and see its topics and questions in one place.", chooseTrack: "Start this track", currentTrack: "Current track", switchTrack: "Select track", trackQuestions: "questions", trackTopics: "topics", whyPrepareHere: "How does the platform prepare you?", whyPrepareHereLead: "From understanding to simulation, every step helps you study with focus and see your real readiness.", feature1Title: "Understand the idea at its source", feature1Lead: "Concise answers, clear explanations, and official references that help the concept stick instead of relying on memorization.", feature2Title: "Practice like it is a real interview", feature2Lead: "Build a complete interview around your target topics and level, then measure your readiness before the big day.", feature3Title: "Review at your own pace", feature3Lead: "Test yourself one question at a time, reveal answers when you need them, and study without countdown pressure.", feature4Title: "See your progress clearly", feature4Lead: "Save important questions and track what you have mastered on your device, with optional secure sync when signed in.",
    sessionEyebrow: "Review session", sessionTitle: "Review session", sessionDescription: "Choose a topic and level, then review in order without a timer or randomization.", chooseTopic: "Choose a topic", chooseDifficulty: "Choose a level", preparing: "Preparing the session…", question: "Question", of: "of", previous: "Previous question", next: "Next question", noCombination: "No questions match this combination", startStudy: "Start a review session", selectSession: "Choose a topic and level to prepare the questions in order.",
    interviewEyebrow: "Full interview", interviewTitle: "Build a complete interview", interviewDescription: "Choose multiple Topics in the Active Track and one level. A higher level includes its own questions and all lower levels.", chooseTopics: "Choose topics", selected: "selected", interviewLevel: "Interview level", inclusiveHint: "The selected level includes every lower level.", preparingInterview: "Preparing the interview…", completeSetup: "Finish setting up the interview", startInterview: "Start full interview", interviewEmpty: "Choose at least one topic and an interview level to prepare your questions.",
    progressEyebrow: "Your progress", progressTitle: "Progress", progressDescription: "Sign in to save your progress and follow it across the Track you choose.", progressSignIn: "Sign in to keep your progress with your account.", progressAuthSetup: "Sign-in is not configured in this environment.", reviewed: "Reviewed", continueReview: "Continue reviewing", reviewing: "Reviewing", mastered: "Mastered", favorites: "Favorites", noQuestions: "No questions here yet.", resetTitle: "Reset local data", resetDescription: "Clears question progress and favorites only.", reset: "Reset progress", resetConfirm: "Are you sure you want to clear progress and favorites on this device?",
    backLibrary: "← Question library", lastReviewed: "Last reviewed", staleReview: "Check the source before your interview if this review date is old.", progressLegend: "Question progress", favorite: "Save to favorites", saved: "Progress saved on this device", reveal: "Reveal answer", hide: "Hide answer", shortAnswer: "Short answer", explanation: "Explanation", code: "Code example", mistakes: "Common mistakes", followUps: "Follow-up questions", sources: "Sources", notFound: "Question not found", databaseQuestionEyebrow: "Database question", databaseQuestionLoading: "Loading question…", databaseQuestionNotFound: "Check the link or return to the question library.", databaseQuestionError: "Could not load the question", databaseQuestionErrorDescription: "There was a temporary connection problem. Try again.", databaseQuestionRetry: "Retry", footer: "Original content with official references.", footerExplore: "Explore", footerPractice: "Practice", footerPolicies: "Policies", privacyPolicy: "Privacy policy", termsOfUse: "Terms of use", sourceCode: "Project on GitHub", footerNote: "General educational content, not legal advice.", footerRights: "© 2026 JahezDev · Some content is licensed CC BY 4.0.", language: "العربية",
    submitEyebrow: "Community contribution", submitTitle: "Suggest an interview question", submitDescription: "Share a useful question and answer. Every contribution is reviewed before it appears in the library.", submitLoading: "Loading account status…", submitSignInRequired: "Sign in to submit a question.", submitTrack: "Track", submitTopics: "Topics", submitQuestion: "Question", submitShortAnswer: "Short answer", submitExplanation: "Explanation", submitDifficulty: "Difficulty", submitSources: "Official sources", submitSourcesHint: "One HTTPS URL per line", submitCode: "Code example (optional)", submitMistakes: "Common mistakes (optional, one per line)", submitFollowups: "Follow-up questions (optional, one per line)", submitDisplayName: "Public username", submitConsent: "I agree to publish this contribution under CC BY 4.0.", submitButton: "Submit for review", submitSubmitting: "Submitting…", submitPending: "Contribution saved; creating the review Issue…", submitSuccess: "Contribution submitted for review.", submitSuccessIssue: "Open GitHub Issue", submitDuplicate: "It may resemble an existing question and will be reviewed", submitFailed: "The review Issue could not be created.", submitRetry: "Retry", submitRateLimit: "Daily limit reached (5 submissions).", submitCooldown: "Wait a minute before sending another contribution.", submitSuspended: "Your account is suspended from submitting contributions.", submitValidation: "Check required fields, links, and content before submitting.", submitUnavailable: "The service is currently unavailable. Try again later.", moderatorLoading: "Loading submissions…", moderatorSignIn: "Sign in to access the moderator console.", moderatorStatus: "Submission status", moderatorRefresh: "Refresh", moderatorEmpty: "No submissions match this status.", moderatorReason: "Decision reason", moderatorChanges: "Request changes", moderatorReject: "Reject submission",
    onboardingEyebrow: "Account setup", onboardingTitle: "Choose your Tracks", onboardingDescription: "Select at least one active Track and choose the Default Track you want to start from.", myTracksTitle: "My Tracks", myTracksDescription: "Add or remove active Track Preferences and change your Default Track. Question Progress, Favorites, and historical Submissions stay untouched.", tracksLoading: "Loading Tracks…", tracksSignIn: "Sign in to manage your Tracks.", tracksAuthSetup: "Track management requires authentication setup first.", tracksLegend: "Track Preferences", defaultTrackLegend: "Default Track", defaultTrackHint: "Your Default Track must be one of your selected Tracks.", unavailableTracksLegend: "Unavailable historical Tracks", trackUnavailable: "Unavailable", tracksRequired: "Select at least one active Track.", defaultTrackRequired: "Choose a Default Track from your selected Tracks.", lastTrackRequired: "You cannot remove the last active Track Preference.", tracksSave: "Save Tracks", tracksSaving: "Saving…", tracksSaved: "Your Track Preferences and Default Track were saved.", tracksUnavailable: "Track Preferences could not be loaded or saved. Try again.", tracksRetry: "Retry", tracksContinue: "Continue", continueBrowsing: "Continue browsing the catalogue", noActiveTracksTitle: "No active Tracks are available", noActiveTracksDescription: "Come back when an active Track is available to finish setup.", tracksRecoveryTitle: "Your selected Tracks are no longer available", tracksRecoveryDescription: "Choose a new active Track to return to Onboarding. Your Question Progress, Favorites, and historical Submissions are preserved.", tracksRecoveryAction: "Return to Onboarding",
  },
} as const;

export function localeFromPathname(pathname: string): Locale {
  return pathname.split("/").filter(Boolean).find((segment) => segment === "en" || segment === "ar") === "en" ? "en" : "ar";
}

export function localeFromLanguageTag(languageTag: string | null | undefined): Locale {
  return /^en(?:-|$)/i.test(languageTag ?? "") ? "en" : "ar";
}

export function localizedHref(locale: Locale, path = "/"): string {
  const [pathname, search = ""] = (path.startsWith("/") ? path : `/${path}`).split("?", 2);
  const cleanPath = pathname === "/" ? "" : pathname.replace(/\/+$/, "");
  const base = `/${locale}${cleanPath}`;
  return search ? `${base}?${search}` : base;
}

export function localeDirection(locale: Locale): "rtl" | "ltr" {
  return locale === "ar" ? "rtl" : "ltr";
}

export function topicName(locale: Locale, topicId: string): string {
  return topicTranslations.en[topicId] ?? topicTranslations[locale]?.[topicId] ?? topicId;
}

function localeWithLatinDigits(locale: Locale): string {
  return locale === "ar" ? "ar-EG-u-nu-latn" : "en-US-u-nu-latn";
}

export function formatNumber(value: number, locale: Locale): string {
  return new Intl.NumberFormat(localeWithLatinDigits(locale)).format(value);
}

const approximateCountTiers = [
  [1, 1, ""], [5, 5, ""], [10, 10, ""], [50, 50, ""], [100, 100, ""], [500, 500, ""],
  [1_000, 1, "K"], [5_000, 5, "K"], [10_000, 10, "K"], [50_000, 50, "K"], [100_000, 100, "K"], [500_000, 500, "K"],
  [1_000_000, 1, "M"], [5_000_000, 5, "M"], [10_000_000, 10, "M"], [50_000_000, 50, "M"], [100_000_000, 100, "M"], [500_000_000, 500, "M"],
  [1_000_000_000, 1, "B"], [5_000_000_000, 5, "B"], [10_000_000_000, 10, "B"],
] as const;

export function formatApproximateCount(value: number, locale: Locale): string {
  const count = Math.max(0, Math.floor(value));
  const tier = [...approximateCountTiers].reverse().find(([minimum]) => count >= minimum);
  return tier ? `+${formatNumber(tier[1], locale)}${tier[2]}` : `+${formatNumber(0, locale)}`;
}

export function formatDate(value: string, locale: Locale): string {
  return new Intl.DateTimeFormat(localeWithLatinDigits(locale), { dateStyle: "medium" }).format(new Date(`${value}T00:00:00Z`));
}
